apiVersion: v1
kind: Pod
metadata:
  name: shiva-app
  labels:
    app: shiva-app
spec:
  containers:
    - name: shiva-app
      image: shivadeshapathi/shiva-app:tagVersion
      ports:
        - containerPort: 8080
